<?php

declare(strict_types=1);

namespace Nowo\ContactFormBundle\DependencyInjection;

use Symfony\Component\Config\Definition\Builder\TreeBuilder;
use Symfony\Component\Config\Definition\ConfigurationInterface;

/**
 * Defines the configuration tree for the contact form bundle.
 */
class Configuration implements ConfigurationInterface
{
    public const ALIAS = 'nowo_contact_form';

    public const CSS_FRAMEWORKS = ['bootstrap', 'bootstrap4', 'bootstrap5', 'tailwind', 'foundation', 'custom', 'tabler', 'none'];

    public function getConfigTreeBuilder(): TreeBuilder
    {
        $treeBuilder = new TreeBuilder(self::ALIAS);
        $rootNode    = $treeBuilder->getRootNode();

        $rootNode
            ->addDefaultsIfNotSet()
            ->children()
                ->scalarNode('client_entity_class')
                    ->defaultNull()
                    ->info('Optional FQCN of the host client entity for linking submissions.')
                ->end()
                ->scalarNode('client_label_property')
                    ->defaultValue('email')
                    ->info('Property or getter used to display linked clients in admin.')
                ->end()
                ->scalarNode('client_user_accessor')
                    ->defaultNull()
                    ->info('Optional method on the authenticated user that returns the client entity (e.g. getClient).')
                ->end()
                ->scalarNode('ip_anonymization_salt')
                    ->defaultValue('%kernel.secret%')
                    ->info('Salt used when hashing IP addresses for GDPR storage.')
                ->end()
                ->integerNode('default_retention_days')
                    ->defaultValue(365)
                    ->min(1)
                    ->info('Default data retention period for new contact forms.')
                ->end()
                ->arrayNode('phone_prefixes')
                    ->info('Default international dialing prefixes for phone fields (code => label).')
                    ->defaultValue([
                        '+34'  => 'ES (+34)',
                        '+1'   => 'US (+1)',
                        '+33'  => 'FR (+33)',
                        '+44'  => 'UK (+44)',
                        '+49'  => 'DE (+49)',
                        '+351' => 'PT (+351)',
                    ])
                    ->normalizeKeys(false)
                    ->scalarPrototype()->end()
                ->end()
                ->arrayNode('phone_input')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->scalarNode('value_format')
                            ->defaultValue('CONCATENATED')
                            ->info('Model format passed to PhoneInputBundle PhoneType (CONCATENATED recommended for submissions).')
                        ->end()
                        ->scalarNode('default_country')
                            ->defaultValue('ES')
                            ->info('Fallback default country ISO when a phone field does not specify one.')
                        ->end()
                        ->booleanNode('country_prefix_selector')
                            ->defaultTrue()
                            ->info('Enable the country prefix selector on PhoneInputBundle fields.')
                        ->end()
                        ->booleanNode('show_flag')
                            ->defaultTrue()
                            ->info('Show country flags in PhoneInputBundle prefix selector.')
                        ->end()
                    ->end()
                ->end()
                ->scalarNode('admin_route_prefix')
                    ->defaultValue('/admin/contact-forms')
                    ->cannotBeEmpty()
                    ->info('URL path prefix for admin CRUD routes (host should lock with security.access_control).')
                ->end()
                ->arrayNode('web_ui')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('enabled')
                            ->defaultTrue()
                            ->info('When false, admin access subscriber is not registered (routes still load; prefer security firewall).')
                        ->end()
                        ->scalarNode('layout_template')
                            ->defaultValue('@NowoContactFormBundle/admin/layout.html.twig')
                            ->cannotBeEmpty()
                            ->info('Twig layout extended by admin pages (global nowo_contact_form_layout_template). Set to your app layout or a one-file bridge.')
                        ->end()
                        ->enumNode('css_framework')
                            ->values(self::CSS_FRAMEWORKS)
                            ->defaultValue('bootstrap5')
                            ->info('Host CSS stack hint: bootstrap5 | bootstrap4 | bootstrap | tailwind | foundation | tabler | custom | none.')
                        ->end()
                        ->enumNode('icon_set')
                            ->values(['bootstrap-icons', 'tabler-icons', 'ux_icon', 'svg_inline', 'none'])
                            ->defaultValue('bootstrap-icons')
                        ->end()
                        ->integerNode('list_page_size')
                            ->defaultValue(20)
                            ->min(1)
                            ->max(200)
                            ->info('Default page size for admin form and submission lists.')
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('security')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->scalarNode('access_checker')
                            ->defaultNull()
                            ->info('Optional service id implementing ContactFormAccessCheckerInterface.')
                        ->end()
                        ->arrayNode('access_roles')
                            ->scalarPrototype()->end()
                            ->defaultValue(['ROLE_ADMIN'])
                            ->info('Roles that may access admin CRUD. Empty disables bundle-level role checks.')
                        ->end()
                        ->booleanNode('allow_unauthenticated')
                            ->defaultFalse()
                            ->info('DEV/DEMO ONLY. When true, admin UI may load without SecurityBundle / without login. Production MUST keep false.')
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('notifications')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('enabled')
                            ->defaultFalse()
                            ->info('Enable submission notifications via ContactSubmissionNotifierInterface.')
                        ->end()
                        ->scalarNode('service')
                            ->defaultNull()
                            ->info('Custom service id implementing ContactSubmissionNotifierInterface (overrides built-in notifiers).')
                        ->end()
                        ->scalarNode('default_recipient')
                            ->defaultNull()
                            ->info('Fallback notification recipient when the form has no notification_email.')
                        ->end()
                        ->arrayNode('mailer')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->booleanNode('enabled')
                                    ->defaultFalse()
                                    ->info('Send email via symfony/mailer when installed.')
                                ->end()
                                ->scalarNode('from')
                                    ->defaultValue('noreply@example.com')
                                    ->info('Sender address for mailer notifications.')
                                ->end()
                                ->scalarNode('subject')
                                    ->defaultValue('New contact submission: {form}')
                                    ->info('Email subject template; {form} is replaced with the form name.')
                                ->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('file_upload')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->scalarNode('service')
                            ->defaultNull()
                            ->info('Custom service id implementing ContactFormFileUploadHandlerInterface (required for file fields).')
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('public_submission_rate_limit')
                    ->addDefaultsIfNotSet()
                    ->info('Rate limit for public form submissions per IP and form slug.')
                    ->children()
                        ->booleanNode('enabled')->defaultTrue()->end()
                        ->integerNode('limit')->defaultValue(5)->min(1)->end()
                        ->integerNode('interval_seconds')->defaultValue(60)->min(1)->end()
                    ->end()
                ->end()
                ->arrayNode('doctrine')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->scalarNode('table_prefix')
                            ->defaultValue('')
                            ->info('Prefix prepended to table names (nowo_contact_form, nowo_contact_submission, …). Empty = no prefix.')
                        ->end()
                    ->end()
                ->end()
            ->end();

        return $treeBuilder;
    }
}
