controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

nowo_contact_form:
    resource: '@NowoContactFormBundle/Resources/config/routes.yaml'

when@dev:
    _dev_routes:
        resource: ../config/routes/dev/
        type: directory
